version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:8.0.3
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - ecomerce_net

  # Redis service
  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - ecomerce_net

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:4.0.3-management-alpine
    container_name: rabbitmq
    ports:
      - '15672:15672' # Management UI
      - '5672:5672' # AMQP protocol
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - ecomerce_net

volumes:
  mongo-data:
  redis-data:
  rabbitmq-data:

# Define the custom network
networks:
  ecomerce_net:
    driver: bridge
