@url_dev = http://localhost:3055/v1/api

### sign up
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: cf4cb94191d67dc27e84e7edc67e77dd7e42a0981ecec4e65b67c0efddf2ea61fa06a5b3b8b01a68a109dffbefb56be26378321967717f7aa8b7aaadba70d262

{
    "name": "Michael1",
    "email": "michael1@gmail.com",
    "password": "abc123"
}